# Generated by Django 2.2.6 on 2020-10-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
